#!/usr/bin/env python3
"""Generate the compact RGB565 WMB+ display logo from the official artwork."""

from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "weighmybru-plus-logo.jpg"
OUTPUT = ROOT / "src" / "WeighMyBruPlusLogo.cpp"
SIZE = 164
COLOR_COUNT = 16


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def format_values(values: list[int], width: int, per_line: int) -> str:
    lines = []
    for offset in range(0, len(values), per_line):
        chunk = values[offset : offset + per_line]
        lines.append("    " + ", ".join(f"0x{value:0{width}X}" for value in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    source = Image.open(SOURCE).convert("RGB")
    resized = ImageOps.fit(source, (SIZE, SIZE), Image.Resampling.LANCZOS)
    indexed = resized.quantize(
        colors=COLOR_COUNT,
        method=Image.Quantize.MEDIANCUT,
        dither=Image.Dither.NONE,
    )

    palette_bytes = indexed.getpalette()[: COLOR_COUNT * 3]
    palette = [
        rgb565(*palette_bytes[index : index + 3])
        for index in range(0, len(palette_bytes), 3)
    ]
    indices = list(indexed.getdata())
    packed = [
        (indices[index] << 4) | indices[index + 1]
        for index in range(0, len(indices), 2)
    ]

    output = f'''// Generated by tools/generate-display-logo.py from the official WMB+ artwork.
#include "WeighMyBruPlusLogo.h"

namespace WeighMyBruPlusLogo {{
const uint16_t PALETTE[COLOR_COUNT] PROGMEM = {{
{format_values(palette, 4, 8)}
}};

const uint8_t PIXELS[PACKED_BYTE_COUNT] PROGMEM = {{
{format_values(packed, 2, 16)}
}};
}}  // namespace WeighMyBruPlusLogo
'''
    OUTPUT.write_text(output, encoding="ascii")
    print(
        f"generated {OUTPUT.relative_to(ROOT)}: "
        f"{len(packed)} packed bytes + {len(palette) * 2} palette bytes"
    )


if __name__ == "__main__":
    main()
