#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Default to the real-HX711 harness env, NOT a *-sim-* env. See wokwi.toml for
# why: WMBP_SIMULATION_MODE=1 bypasses the HX711 pin path entirely.
env_name="${1:-esp32s3-xiao-wokwi-hx711-dout-interrupt}"
timeout_ms="${WMBP_WOKWI_TIMEOUT_MS:-35000}"
run_name="${WMBP_WOKWI_RUN_NAME:-${env_name}}"
out_dir="${WMBP_WOKWI_OUTPUT_DIR:-${repo_root}/.pio/wokwi/runs/${run_name}}"
project_dir="${out_dir}/project"
log_file="${out_dir}/serial.log"
json_file="${out_dir}/analysis.json"
wokwi_stdout_file="${out_dir}/wokwi-cli.log"
vcd_file="${out_dir}/logic.vcd"
diagram_file="${WMBP_WOKWI_DIAGRAM:-${repo_root}/diagram.json}"
scenario_file="${WMBP_WOKWI_SCENARIO:-${repo_root}/wokwi/usb-weight-stream.scenario.yaml}"
firmware_bin="${repo_root}/.pio/build/${env_name}/firmware.bin"
firmware_elf="${repo_root}/.pio/build/${env_name}/firmware.elf"

case "${timeout_ms}" in
  ''|*[!0-9]*) echo "WMBP_WOKWI_TIMEOUT_MS must be a positive integer." >&2; exit 2 ;;
esac
simulation_timeout_seconds="$(( (timeout_ms + 999) / 1000 ))"
budget_seconds="${WMBP_WOKWI_BUDGET_SECONDS:-0}"
case "${budget_seconds}" in
  ''|*[!0-9]*) echo "WMBP_WOKWI_BUDGET_SECONDS must be a positive integer." >&2; exit 2 ;;
esac
if [[ "${WMBP_WOKWI_RUN_CONFIRMED:-0}" != "1" || "${budget_seconds}" -lt "${simulation_timeout_seconds}" ]]; then
  cat >&2 <<EOF
REFUSING TO RUN WOKWI without an explicit confirmation and sufficient budget.

  requested timeout: ${simulation_timeout_seconds}s
  approved budget:   ${budget_seconds}s

Prefer the guarded matrix runner:
  tools/run-wokwi-matrix.sh --dry-run PROFILE
  tools/run-wokwi-matrix.sh --budget-seconds N PROFILE

For a direct run, set both WMBP_WOKWI_RUN_CONFIRMED=1 and
WMBP_WOKWI_BUDGET_SECONDS to at least ${simulation_timeout_seconds}.
EOF
  exit 2
fi

# ---------------------------------------------------------------------------
# Sim-env guard.
#
# A *-sim-* build never reads DT/SCK, so the Wokwi HX711 part cannot influence
# it. Running a DOUT/acquisition scenario against a sim build produces a
# green result that means nothing. Hard-fail that combination; warn on the
# merely-suspicious ones.
# ---------------------------------------------------------------------------
is_sim_env=0
case "${env_name}" in *-sim-*) is_sim_env=1 ;; esac

if [[ "${is_sim_env}" == "1" ]]; then
  case "${scenario_file}${diagram_file}" in
    *dout*|*missed-ready*|*missedReady*)
      cat >&2 <<EOF
REFUSING TO RUN: acquisition scenario/diagram against a simulation build.

  env:      ${env_name}      (WMBP_SIMULATION_MODE=1 -> HX711 pins unused)
  scenario: ${scenario_file}
  diagram:  ${diagram_file}

Scale::getWeight() takes the '#if WMBP_SIMULATION_MODE' branch in this build,
so DT/SCK are never driven and missedReadyEvery has no effect. The run would
pass while exercising none of the acquisition path.

Use a harness env instead, e.g.:
  tools/run-wokwi-runtime-smoke.sh esp32s3-xiao-wokwi-hx711-dout-interrupt

Set WMBP_WOKWI_ALLOW_SIM_ACQUISITION=1 to override (not recommended).
EOF
      [[ "${WMBP_WOKWI_ALLOW_SIM_ACQUISITION:-0}" == "1" ]] || exit 2
      ;;
  esac
  echo "NOTE: ${env_name} is a simulation build - the HX711 pin path is bypassed." >&2
  echo "      Cadence is generated by the firmware loop, not by the Wokwi chip." >&2
fi

# ---------------------------------------------------------------------------
# Rate floor.
#
# Harness envs: the Wokwi chip drives cadence at diagram actualSps (94.22), so
#   the real ~80 SPS-class floor applies.
# Sim envs: cadence is gated by loop iterations, and Wokwi's ESP32-S3 model
#   cannot sustain 80 Hz - observed 40.37/40.75 Hz on beta6/beta7. A 78 Hz floor
#   fails unconditionally there and therefore discriminates nothing. 35.0 keeps
#   headroom below the observed floor while still catching a real collapse.
# Recalibrate if the diagram's actualSps or the scenario duration changes.
# ---------------------------------------------------------------------------
if [[ "${is_sim_env}" == "1" ]]; then
  default_min_rate_hz=35.0
else
  default_min_rate_hz=78.0
fi

if ! command -v wokwi-cli >/dev/null 2>&1; then
  cat >&2 <<'EOF'
wokwi-cli is not installed.

Install:
  curl -L https://wokwi.com/ci/install.sh | sh

Then set your Wokwi token:
  export WOKWI_CLI_TOKEN=...

EOF
  exit 127
fi

if [[ -z "${WOKWI_CLI_TOKEN:-}" ]]; then
  cat >&2 <<'EOF'
WOKWI_CLI_TOKEN is not set.

Create a Wokwi CI token, then run:
  export WOKWI_CLI_TOKEN=...

EOF
  exit 2
fi

cd "${repo_root}"
if [[ "${WMBP_WOKWI_SKIP_BUILD:-0}" == "1" ]]; then
  missing_artifact=0
  if [[ ! -f "${firmware_bin}" ]]; then
    echo "WMBP_WOKWI_SKIP_BUILD=1 but firmware image is missing: ${firmware_bin}" >&2
    missing_artifact=1
  fi
  if [[ ! -f "${firmware_elf}" ]]; then
    echo "WMBP_WOKWI_SKIP_BUILD=1 but firmware ELF is missing: ${firmware_elf}" >&2
    missing_artifact=1
  fi
  [[ "${missing_artifact}" == "0" ]] || exit 2
  echo "Skipping PlatformIO build; using existing Wokwi firmware artifacts for ${env_name}."
else
  pio run -e "${env_name}"
fi

rm -rf "${project_dir}"
mkdir -p "${project_dir}"
mkdir -p "${project_dir}/chips"

firmware_rel="$(python3 -c 'import os, sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))' "${firmware_bin}" "${project_dir}")"
elf_rel="$(python3 -c 'import os, sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))' "${firmware_elf}" "${project_dir}")"

cat > "${project_dir}/wokwi.toml" <<EOF
[wokwi]
version = 1
firmware = "${firmware_rel}"
elf = "${elf_rel}"
EOF

if [[ ! -f "${diagram_file}" ]]; then
  echo "Wokwi diagram not found: ${diagram_file}" >&2
  exit 2
fi

cp "${diagram_file}" "${project_dir}/diagram.json"
mkdir -p "${project_dir}/wokwi"
if [[ ! -f "${scenario_file}" ]]; then
  echo "Wokwi scenario not found: ${scenario_file}" >&2
  exit 2
fi

cp "${scenario_file}" "${project_dir}/wokwi/runtime-smoke.scenario.yaml"

while IFS= read -r chip_base; do
  [[ -n "${chip_base}" ]] || continue
  chip_source="${repo_root}/wokwi/${chip_base}.chip.c"
  chip_json="${repo_root}/wokwi/${chip_base}.chip.json"
  if [[ ! -f "${chip_source}" ]]; then
    echo "Wokwi custom chip source not found for chip-${chip_base}: ${chip_source}" >&2
    exit 2
  fi
  if [[ ! -f "${chip_json}" ]]; then
    echo "Wokwi custom chip JSON not found for ${chip_source}: ${chip_json}" >&2
    exit 2
  fi
  echo "Compiling Wokwi custom chip: ${chip_base}"
  wokwi-cli chip compile "${chip_source}" -o "${project_dir}/chips/${chip_base}.chip.wasm"
  cp "${chip_json}" "${project_dir}/chips/${chip_base}.chip.json"
  cat >> "${project_dir}/wokwi.toml" <<EOF

[[chip]]
name = '${chip_base}'
binary = 'chips/${chip_base}.chip.wasm'
EOF
done < <(jq -r '.parts[]?.type | select(startswith("chip-")) | sub("^chip-"; "")' "${diagram_file}" | sort -u)

echo "Running Wokwi runtime smoke for ${env_name}"
echo "Diagram: ${diagram_file}"
echo "Scenario: ${scenario_file}"
echo "Min device rate gate: ${WMBP_WOKWI_MIN_DEVICE_RATE_HZ:-${default_min_rate_hz}} Hz"
echo "Serial log: ${log_file}"
echo "Wokwi CLI log: ${wokwi_stdout_file}"

wokwi_args=(
  "${project_dir}"
  --scenario "wokwi/runtime-smoke.scenario.yaml"
  --serial-log-file "${log_file}"
  --timeout "${timeout_ms}"
  --timeout-exit-code 0
)
# Requires a wokwi-logic-analyzer part in the diagram (diagram.xiao-94hz-logic.json).
# Captured channels are checked by tools/check-hx711-vcd.py.
if [[ "${WMBP_WOKWI_VCD:-0}" == "1" ]]; then
  wokwi_args+=(--vcd-file "${vcd_file}")
  echo "VCD capture: ${vcd_file}"
fi

outer_timeout_seconds="$(( simulation_timeout_seconds * ${WMBP_WOKWI_WALL_TIME_MULTIPLIER:-3} + ${WMBP_WOKWI_CLI_GRACE_SECONDS:-30} ))"
wokwi-cli "${wokwi_args[@]}" \
  >"${wokwi_stdout_file}" 2>&1 &
wokwi_pid="$!"
wokwi_status=0
wokwi_started_at="${SECONDS}"
wokwi_watchdog_fired=0

while kill -0 "${wokwi_pid}" >/dev/null 2>&1; do
  if (( SECONDS - wokwi_started_at > outer_timeout_seconds )); then
    echo "Wokwi CLI did not exit within ${outer_timeout_seconds}s; stopping hung run." >&2
    kill "${wokwi_pid}" >/dev/null 2>&1 || true
    sleep 2
    kill -9 "${wokwi_pid}" >/dev/null 2>&1 || true
    wait "${wokwi_pid}" >/dev/null 2>&1 || true
    tail -n 160 "${wokwi_stdout_file}" >&2 || true
    wokwi_watchdog_fired=1
    break
  fi
  sleep 1
done

if [[ "${wokwi_watchdog_fired}" == "0" ]]; then
  set +e
  wait "${wokwi_pid}"
  wokwi_status="$?"
  set -e
else
  wokwi_status=124
fi

if [[ "${wokwi_status}" != "0" ]]; then
  if [[ "${wokwi_status}" == "124" && -s "${log_file}" && "${WMBP_WOKWI_ANALYZE_AFTER_WATCHDOG:-1}" == "1" ]]; then
    echo "Wokwi CLI was stopped by watchdog; analyzing captured serial log." >&2
  else
    tail -n 160 "${wokwi_stdout_file}" >&2 || true
    exit "${wokwi_status}"
  fi
fi

analyzer_args=(
  "${repo_root}/tools/analyze-wmbp-serial-log.py"
  "${log_file}"
  --label "wokwi:${env_name}"
  --json-output "${json_file}"
  --min-device-rate-hz "${WMBP_WOKWI_MIN_DEVICE_RATE_HZ:-${default_min_rate_hz}}"
  --max-device-gap-ms "${WMBP_WOKWI_MAX_DEVICE_GAP_MS:-150.0}"
  --max-gaps-over-100ms "${WMBP_WOKWI_MAX_GAPS_OVER_100MS:-0}"
)

if [[ "${WMBP_WOKWI_NO_FAIL:-0}" == "1" ]]; then
  analyzer_args+=(--no-fail)
fi

python3 "${analyzer_args[@]}"

echo "Analysis JSON: ${json_file}"
